export const agendaData = [
  { day: '12', mouth: '06', place: 'Natal-RN' },
  { day: '13', mouth: '06', place: 'João Pessoa-PB' },
  { day: '14', mouth: '06', place: 'Recife-PE' },
  { day: '15', mouth: '06', place: 'Maceió-AL' },
  { day: '16', mouth: '06', place: 'Salvador-BA' },
  { day: '19', mouth: '06', place: 'Campinas-SP' },
  { day: '20', mouth: '06', place: 'São Paulo-SP' },
  { day: '21', mouth: '06', place: 'Belo Horizonte-MG' },
  { day: '22', mouth: '06', place: 'Vitória-ES' },
  { day: '23', mouth: '06', place: 'Brasília-DF' },
  { day: '28', mouth: '06', place: 'Curitiba-PR' },
  { day: '29', mouth: '06', place: 'Florianópolis-SC' },
  { day: '30', mouth: '06', place: 'Porto Alegre-RS' },
  { day: '03', mouth: '07', place: 'Teresina-PI' },
  { day: '04', mouth: '07', place: 'São Luís-MA' },
  { day: '05', mouth: '07', place: 'Fortaleza-CE' },
  { day: '06', mouth: '07', place: 'Belém-PA' },
  { day: '07', mouth: '07', place: 'Manaus-AM' },
  { day: '10', mouth: '07', place: 'Porto Velho-RO' },
  { day: '11', mouth: '07', place: 'Cuiabá-MT' },
  { day: '12', mouth: '07', place: 'Campo Grande-MS' },
  { day: '13', mouth: '07', place: 'Rio de Janeiro-RJ' },
  { day: '14', mouth: '07', place: 'Aracaju-SE' },
  { day: '20', mouth: '07', place: 'Debate' },
]